FROM mcr.microsoft.com/java/jdk:8-zulu-alpine AS first
COPY /source /usr/src/app
WORKDIR /usr/src/app
RUN javac uygulama.java

FROM mcr.microsoft.com/java/jre:8-zulu-alpine
WORKDIR /app
COPY --from=first /usr/src/app .
CMD ["java", "uygulama"]